apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - list:
            elements:
              - name: vault
                namespace: vault
                chart: vault
                repo: https://helm.releases.hashicorp.com
                version: 0.29.1
        - git:
            repoURL: 'https://{{ .Values.github_server }}/{{ .Values.config_org }}/{{ .Values.config_repo }}.git'
            revision: main
            files:
              - path: observability-cluster/config/cluster-params.yaml
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{.repo}}'
        chart: '{{.chart}}'
        targetRevision: '{{.version}}'
        helm:
          values: |
            global:
              enabled: true
            csi:
              enabled: true
            injector:
              enabled: true
            server:
              enabled: true
              dataStorage:
                storageClass: '{{.storageClass}}'
              serviceAccount:
                name: vault
              standalone:
                config: |
                  ui = true
                  listener "tcp" {
                    tls_disable = 1
                    address = "[::]:8200"
                    cluster_address = "[::]:8201"
                  }
                  storage "file" {
                    path = "/vault/data"
                  }
              ingress:
                enabled: true
                ingressClassName: nginx
                annotations:
                  cert-manager.io/cluster-issuer: local-ca-issuer
                  cert-manager.io/duration: 2160h
                  cert-manager.io/renew-before: 360h
                tls:
                  - secretName: vault-tls
                    hosts:
                      - vault.{{.dnsSuffix}}
                hosts:
                  - host: vault.{{.dnsSuffix}}
              extraVolumes:
              - type: configMap
                name: local-ca
              extraVolumeMounts:
              - name: local-ca
                mountPath: /etc/ssl/certs/local-ca.pem
                subPath: CA.cer
                readOnly: false
              hostAliases:
              - ip: '{{.clusterIP}}'
                hostnames:
                - vault.{{.dnsSuffix}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true