apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: update-bitnami-image-policy
spec:
  rules:
  - name: "Update bitnami/kubectl to bitnamilegacy/kubectl"
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - kyverno
    mutate:
      foreach:
      - list: "request.object.spec.containers"
        patchStrategicMerge:
          spec:
            containers:
            - (name): "{{ element.name }}"
              image: "{{ regex_replace('^bitnami/kubectl', 'bitnamilegacy/kubectl', element.image) }}"
      - list: "request.object.spec.initContainers"
        patchStrategicMerge:
          spec:
            initContainers:
            - (name): "{{ element.name }}"
              image: "{{ regex_replace('^bitnami/kubectl', 'bitnamilegacy/kubectl', element.image) }}"
