apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
          - list:
              elements:
                - name: grafana
                  namespace: grafana
                  chart: grafana
                  repo: https://grafana.github.io/helm-charts
                  version: 6.58.5
          - git:
              repoURL: 'https://{{ .Values.github_server }}/{{ .Values.config_org }}/{{ .Values.config_repo }}.git'
              revision: main
              files:
                - path: "observability-cluster/config/cluster-params.yaml"
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{.repo}}'
        chart: '{{.chart}}'
        targetRevision: '{{.version}}'
        helm:
          values: |
            admin:
              existingSecret: grafana-admin-credentials
              userKey: admin-user
              passwordKey: admin-password
            grafana.ini:
              server:
                root_url: "https://grafana.{{.dnsSuffix}}"
                enable_gzip: true
              auth:
                oauth_allow_insecure_email_lookup: true
            hostAliases:
            - ip: '{{.clusterIP}}'
              hostnames:
              - loki.{{.dnsSuffix}}
              - tempo.{{.dnsSuffix}}
              - victoria-metrics.{{.dnsSuffix}}
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: local-ca-issuer
              hosts:
                - grafana.{{.dnsSuffix}}
              tls:
                - secretName: grafana-tls
                  hosts:
                    - grafana.{{.dnsSuffix}}
            sidecar:
              dashboards:
                enabled: true
                label: grafana_dashboard
                labelValue: "1"
                searchNamespace: ALL
            extraSecretMounts:
              - name: grafana-datasources
                secretName: grafana-datasources
                defaultMode: 0440
                mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
                subPath: datasources.yaml
                readOnly: true
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true
