apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel-collector
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - list:
            elements:
              - name: otel-collector
                namespace: otel-collector
                chart: opentelemetry-collector
                repo: https://open-telemetry.github.io/opentelemetry-helm-charts
                version: 0.139.1
        - git:
            repoURL: 'https://{{ .Values.github_server }}/{{ .Values.config_org }}/{{ .Values.config_repo }}.git'
            revision: main
            files:
              - path: "observability-cluster/config/cluster-params.yaml"
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: '{{.repo}}'
        chart: '{{.chart}}'
        targetRevision: '{{.version}}'
        helm:
          values: |
            fullnameOverride: otel-collector
            serviceAccount:
              create: true
              automountServiceAccountToken: true
            image:
              repository: "otel/opentelemetry-collector-contrib"
              tag: "0.139.0"
            mode: daemonset
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet
            extraEnvs:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # Keep CA volume just in case
            extraVolumes:
            - name: local-ca
              configMap:
                name: local-ca
            extraVolumeMounts:
            - name: local-ca
              mountPath: /etc/ssl/certs/ca.crt
              subPath: CA.cer
            clusterRole:
              create: true
              rules:
              - apiGroups: [""]
                resources: ["nodes", "nodes/proxy", "nodes/metrics", "services", "endpoints", "pods"]
                verbs: ["get", "list", "watch"]
              - nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
                verbs: ["get"]
            presets:
              logsCollection:
                enabled: true
                includeCollectorLogs: true
              hostMetrics:
                enabled: true
              kubeletMetrics:
                enabled: false # Disable standard kubeletstats receiver in favor of direct prometheus scrape for compatibility
              kubernetesAttributes:
                enabled: true
            config:
              receivers:
                hostmetrics:
                  collection_interval: 10s
                  scrapers:
                    cpu: {}
                    memory: {}
                    load: {}
                    network: {}
                    disk: {}
                    filesystem: {}
                
                # Scrape cAdvisor directly to get container_... metrics for standard dashboards
                prometheus:
                  config:
                    scrape_configs:
                      - job_name: 'node-exporter'
                        scrape_interval: 15s
                        static_configs:
                          - targets: ['localhost:9100']
                            labels:
                              instance: '${env:K8S_NODE_NAME}'
                      - job_name: 'kubernetes-cadvisor'
                        scheme: https
                        tls_config:
                          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                          insecure_skip_verify: true
                        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                        kubernetes_sd_configs:
                        - role: node
                        relabel_configs:
                        # Only scrape the node this agent is running on
                        - source_labels: [__meta_kubernetes_node_name]
                          action: keep
                          regex: ${env:K8S_NODE_NAME}
                        - action: labelmap
                          regex: __meta_kubernetes_node_label_(.+)
                        - target_label: __metrics_path__
                          replacement: /metrics/cadvisor
                        metric_relabel_configs:
                          # Drop high cardinality labels or unused metrics if needed
                          - source_labels: [__name__]
                            regex: 'container_tasks_state|container_memory_failures_total'
                            action: drop

              processors:
                transform:
                  error_mode: ignore
                  metric_statements:
                    - context: datapoint
                      statements:
                        - set(attributes["pod"], resource.attributes["k8s.pod.name"])
                        - set(attributes["pod_name"], resource.attributes["k8s.pod.name"])
                        - set(attributes["namespace"], resource.attributes["k8s.namespace.name"])
                        - set(attributes["node"], resource.attributes["k8s.node.name"])
                        - set(attributes["host"], resource.attributes["host.name"])
                        - set(attributes["cluster"], resource.attributes["cluster"])
                        - set(attributes["container"], resource.attributes["k8s.container.name"])
                        - set(attributes["container_name"], resource.attributes["k8s.container.name"])
                  log_statements:
                    - context: log
                      statements:
                        - set(attributes["pod"], resource.attributes["k8s.pod.name"])
                        - set(attributes["namespace"], resource.attributes["k8s.namespace.name"])
                        - set(attributes["node"], resource.attributes["k8s.node.name"])
                        - set(attributes["container"], resource.attributes["k8s.container.name"])
                k8sattributes:
                  auth_type: "serviceAccount"
                  passthrough: false
                  filter:
                    node_from_env_var: K8S_NODE_NAME 
                  extract:
                    metadata:
                      - k8s.node.name
                      - k8s.pod.name
                      - k8s.pod.uid
                      - k8s.namespace.name
                      - k8s.container.name
                  pod_association:
                    - sources:
                        - from: resource_attribute
                          name: k8s.pod.name
                    - sources:
                        - from: resource_attribute
                          name: k8s.pod.uid
                    - sources:
                        - from: connection
                resource/set_unique_host:
                  attributes:
                    - key: host.name
                      value: "${env:K8S_NODE_NAME}"
                      action: upsert
                    - key: instance
                      value: "${env:K8S_NODE_NAME}"
                      action: upsert
                resource/set_cluster:
                  attributes:
                    - key: cluster
                      value: "local-cluster"
                      action: upsert
                batch: {}
                memory_limiter:
                  check_interval: 1s
                  limit_percentage: 75
                  spike_limit_percentage: 15
              exporters:
                otlp:
                  endpoint: "otel-gateway:4317"
                  tls:
                    insecure: true
              service:
                pipelines:
                  traces:
                    receivers: [otlp]
                    processors: [memory_limiter, batch]
                    exporters: [otlp]
                  metrics:
                    receivers: [prometheus, hostmetrics]
                    processors: [memory_limiter, k8sattributes, resource/set_unique_host, resource/set_cluster, transform, batch]
                    exporters: [otlp]
                  logs:
                    receivers: [otlp, filelog]
                    processors: [memory_limiter, k8sattributes, transform, batch]
                    exporters: [otlp]
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true
