apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: splunk-hec-secret
  namespace: otel-collector
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: splunk-hec-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: splunk-hec-secret
