apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - list:
            elements:
              - name: metallb
                namespace: metallb-system
                chart: metallb
                repo: https://metallb.github.io/metallb
                version: 0.14.5
        - git:
            repoURL: 'https://{{ .Values.github_server }}/{{ .Values.config_org }}/{{ .Values.config_repo }}.git'
            revision: main
            files:
              - path: observability-cluster/config/cluster-params.yaml
  template:
    metadata:
      name: '{{ "{{" }}.name}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
        argocd.argoproj.io/refresh: "hard"
    spec:
      project: default
      source:
        repoURL: '{{ "{{" }}.repo}}'
        chart: '{{ "{{" }}.chart}}'
        targetRevision: '{{ "{{" }}.version}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{ "{{" }}.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Replace=true
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
